SELECT 
  CATEGORY,
  PRICE AS MAX_PRICE,
  PRODUCT_NAME
FROM 
  (
    SELECT 
      CATEGORY, 
      PRICE,
      PRODUCT_NAME,
      RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK
    FROM 
      FOOD_PRODUCT
    WHERE 
      CATEGORY IN ('과자', '국', '김치', '식용유')
  ) FP
WHERE 
  PRICE_RANK = 1
ORDER BY 
  MAX_PRICE DESC;
